apiVersion: batch/v1
kind: Job
metadata:
  name: bots-create-superuser
  labels:
    app: bots-edi
    component: init
spec:
  ttlSecondsAfterFinished: 300  # Clean up 5 minutes after completion
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: bots-edi
        component: init
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      
      restartPolicy: OnFailure
      
      containers:
      - name: create-superuser
        image: harbor.pminc.me/priv/bots-edi:latest
        imagePullPolicy: Always
        
        command: ["/bin/sh", "-c"]
        args:
        - |
          #!/bin/sh
          set -e
          
          echo "[INFO] Creating Django superuser (idempotent)..."
          
          # Initialize Django environment
          export DJANGO_SETTINGS_MODULE=settings
          
          # Create superuser using Django shell (idempotent)
          python << 'PYEOF'
          import os
          import sys
          import django
          
          # Setup Django
          sys.path.insert(0, '/config')
          os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'
          django.setup()
          
          from django.contrib.auth import get_user_model
          from django.db import IntegrityError
          
          User = get_user_model()
          
          username = os.environ.get('SUPERUSER_USERNAME', 'admin')
          email = os.environ.get('SUPERUSER_EMAIL', 'admin@localhost')
          password = os.environ.get('SUPERUSER_PASSWORD', 'changeme')
          
          try:
              # Check if user exists
              user = User.objects.get(username=username)
              print(f"[INFO] User '{username}' already exists")
              
              # Update password and email if they've changed
              user.email = email
              user.set_password(password)
              user.is_superuser = True
              user.is_staff = True
              user.save()
              print(f"[INFO] Updated user '{username}' password and permissions")
              
          except User.DoesNotExist:
              # Create new superuser
              user = User.objects.create_superuser(
                  username=username,
                  email=email,
                  password=password
              )
              print(f"[SUCCESS] Created superuser '{username}'")
          
          print(f"[INFO] Superuser '{username}' is ready")
          print(f"[INFO] Email: {email}")
          print(f"[INFO] Permissions: superuser={user.is_superuser}, staff={user.is_staff}")
          PYEOF
          
          echo "[SUCCESS] Superuser creation complete"
        
        env:
        - name: BOTSENV
          value: "default"
        
        envFrom:
        - secretRef:
            name: bots-edidb-secret
        - secretRef:
            name: bots-superuser-secret
            optional: false
        
        volumeMounts:
        - name: data
          mountPath: /home/bots/.bots
        - name: config-ini
          mountPath: /config/bots.ini
          subPath: bots.ini
        - name: config-settings
          mountPath: /config/settings.py
          subPath: settings.py
        
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: bots-edi-data-pvc
      - name: config-ini
        configMap:
          name: bots-config-ini
      - name: config-settings
        configMap:
          name: bots-config-settings
