# Generated by Django 3.2.9 on 2022-01-17 16:21

import bots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='dirmonitor',
            field=models.BooleanField(default=False, help_text='Monitor fromchannel (file) with bots-dirmonitor to trigger this route.'),
        ),
    ]
