# Generated by Django 3.2.9 on 2022-01-17 16:21

import bots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filereport',
            name='divtext',
            field=bots.models.StripCharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='filereport',
            name='rsrv1',
            field=bots.models.StripCharField(blank=True, max_length=128, null=True),
        ),
    ]
