# Generated by Django 3.2.9 on 2022-01-17 16:21

import bots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='debug',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Channel communication debug level: ftp (0 > 2), pop3 (0 > 2), imap4 (0 > 5), http (0 > 5), sftp (0=nolog, 1=critical, 2=error, 3=warn, 4=info, 5=debug)', null=True, verbose_name='Debug level'),
        ),
    ]
