# Generated by Django 3.2.11 on 2022-02-01 15:17

import bots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='rsrv1',
            field=bots.models.StripCharField(blank=True, max_length=256, null=True),
        ),
    ]
