# Generated by Django 3.2.9 on 2022-01-17 16:21

import bots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='secret',
            field=bots.models.StripCharField(blank=True, max_length=256, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='username',
            field=bots.models.StripCharField(blank=True, max_length=256, verbose_name='username'),
        ),
    ]
