# Generated by Django 3.2.9 on 2022-01-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_channel_add_debug'),
        ('bots', '0002_channel_alter_auth_256'),
        ('bots', '0002_channel_alter_inorout_3'),
        ('bots', '0002_filereport_alter_divtext_rsrv1_128'),
        ('bots', '0002_report_alter_rsrv1_256'),
        ('bots', '0002_routes_add_dirmonitor'),
    ]

    operations = [
    ]
