apiVersion: apps/v1
kind: Deployment
metadata:
  name: bots-webserver
  labels:
    app: bots-edi
    component: webserver
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: bots-edi
      component: webserver
  template:
    metadata:
      labels:
        app: bots-edi
        component: webserver
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/health/ping"
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        fsGroupChangePolicy: "OnRootMismatch"
      
           
      containers:
      - name: webserver
        image: harbor.pminc.me/priv/bots-edi-k3s:latest
        imagePullPolicy: Always
        
        command: ["/entrypoint.sh"]
        args: ["webserver"]
        
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        
        envFrom:
        - configMapRef:
            name: bots-env-config
        - secretRef:
            name: bots-edidb-secret
        
        env:
        # Override/add specific env vars here if needed
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: bots-edidb-secret
              key: DJANGO_SECRET_KEY
              optional: true
        
        volumeMounts:
        - name: data
          mountPath: /home/bots/.bots
        - name: config-ini
          mountPath: /config/bots.ini
          subPath: bots.ini
        - name: config-settings
          mountPath: /config/settings.py
          subPath: settings.py
        
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 2
        
        startupProbe:
          httpGet:
            path: /health/startup
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 30  # Allow up to 150 seconds for startup
      
      - name: filebrowser
        image: harbor.pminc.me/priv/filebroswer-bots:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: filebrowser
          protocol: TCP
        envFrom:
        - configMapRef:
            name: bots-env-config
        - secretRef:
            name: bots-superuser-secret
            optional: false
        volumeMounts:
        - name: data
          mountPath: /home/bots/.bots
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: bots-edi-data-pvc
      - name: config-ini
        configMap:
          name: bots-config-ini
      - name: config-settings
        configMap:
          name: bots-config-settings
      
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
