---
apiVersion: v1
kind: Secret
metadata:
  name: bots-edidb-secret
  labels:
    environment: {{ env }}
    app: bots-edi
type: Opaque
stringData:
  # Database Configuration
  DB_NAME: botsedi_data
  DB_USER: botsedi
  DB_HOST: HOST
  DB_PORT: "3306"
  
  # Optional: SMTP Configuration
  SMTP_HOST: HOST
  SMTP_PORT: "587"
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  SMTP_FROM: "Bots EDI <bots@pminc.me>"
  


  DB_PASSWORD: PASSWORD
  DJANGO_SECRET_KEY: GENERATEDKEY
