---
apiVersion: v1
kind: Secret
metadata:
  name: bots-superuser-secret
  labels:
    environment: {{ env }}
    app: bots-edi
type: Opaque
stringData:
  SUPERUSER_USERNAME: USERNAME
  SUPERUSER_EMAIL: user@example.com
  SUPERUSER_PASSWORD: STRONG_PASSWORD
